---
title: "Halifax Housing EDA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(dplyr)
library(ggplot2)
library(plotly)
```

```{r}
vouchers <- readxl::read_excel(here("data", "original", "Housing", "housing_voucher_data.xlsx"))

auth_vouchers <- vouchers %>%
  pivot_longer(cols = contains("authorized_vouchers"), names_to = "year", names_prefix = "authorized_vouchers", values_to = "authorized_vouchers") %>%
  select(state, code, agency_name, year, authorized_vouchers)

num_using_vouchers <- vouchers %>%
  pivot_longer(cols = contains("num_families_using_vouchers"), names_to = "year", names_prefix = "num_families_using_vouchers", values_to = "num_families_using_vouchers") %>%
  select(state, code, agency_name, year, num_families_using_vouchers)

pct_vouchers_in_use <- vouchers %>%
  pivot_longer(cols = contains("Percent of authorized vouchers in use"), names_to = "year", names_prefix = "Percent of authorized vouchers in use", values_to = "pct_vouchers_in_use") %>%
  select(state, code, agency_name, year, pct_vouchers_in_use)

total_payments <- vouchers %>%
  pivot_longer(cols = contains("total_assistance_payments_owners"), names_to = "year", names_prefix = "total_assistance_payments_owners", values_to = "total_assistance_payments_owners") %>%
  select(state, code, agency_name, year, "total_assistance_payments_owners")

vouchers_long <- full_join(full_join(full_join(auth_vouchers, num_using_vouchers), pct_vouchers_in_use), total_payments)
```

```{r}
vouchers_long %>% filter(state == "Virginia") %>%
  ggplot() +
  geom_line(aes(x = year, y = authorized_vouchers, group = agency_name)) +
  theme(legend.position = "none")
```

```{r}
vouchers_long %>% filter(state == "Virginia") %>%
  ggplot() +
  geom_line(aes(x = as.numeric(year), y = num_families_using_vouchers, group = agency_name)) +
  theme(legend.position = "none")
```

```{r}
plot <- vouchers_long %>% filter(state == "Virginia") %>%
  ggplot() +
  geom_line(aes(x = year, y = pct_vouchers_in_use, group = agency_name, color = agency_name)) +
  theme(legend.position = "none")

ggplotly(plot)
```

```{r}
vouchers_long %>% filter(state == "Virginia") %>%
  ggplot() +
  geom_line(aes(x = year, y = total_assistance_payments_owners, group = agency_name)) +
  theme(legend.position = "none")
```
