---
title: "Crimes"
description: "What are the trends in crimes in Halifax?"
tags: ["R", "Visualization"]
weight: 3
draft: false
output: html_document
---
 
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 15, fig.height = 10)

options(scipen = 10000)
```

```{r load_libs_data}
library(here)
library(dplyr)
library(readr)
library(lubridate)
library(ggplot2)
library(maps)
library(rnaturalearth)
library(rnaturalearthdata)
library(stringr)
library(tidycensus)
library(sf)
library(cowplot)

# all VA crimes between 2010 and 2019
all_va_crime <- vroom::vroom(here("data", "original", "Crime", "full_va_crime", "clean_all_arrest_all_years.csv"))

# VA county population by race from census
va_pop_by_race <- read_csv(here("data", "original", "Crime", "full_va_crime", "clean_county_pop_by_race.csv"))

# all Halifax county crimes between 2010 and 2019
halifax_crime <- all_va_crime[all_va_crime$county_cap == "HALIFAX",]


theme_set(theme_minimal() +
            theme(plot.title = element_text(hjust = 0.5, color = "gray10", size = 24),
                  plot.subtitle = element_text(hjust = 0.5, color = "gray30", face = "italic", size = 20),
                  axis.title = element_text(size = 20, color = "gray10"),
                  axis.text = element_text(size = 18, color = "gray30"),
                  strip.text = element_text(size = 22, color = "gray30"),
                  panel.spacing = unit(4, "lines"),
                  legend.key.size = unit(3, "line"),
                  legend.text = element_text(size = 16, color = "gray30"),
                  legend.title = element_text(size = 22, color = "gray10")))

cbbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

```

### Halifax county crime trends

#### Overall crime trends over time

```{r halifax_crimes}
halifax_crime %>%
  group_by(incident_year) %>%
  tally %>%
  ggplot(aes(x = incident_year, y = n)) + 
  geom_bar(stat = 'identity', fill = "#0072B2") + 
  scale_x_continuous(breaks = c(seq(2010, 2019)),
                     labels = c(seq(2010, 2019))) +
  labs(y = "Number of Crimes",
       x = NULL,
       title = "Total Number of Crimes from 2010 to 2019")
```

#### Most common offense types and clearance rates

```{r halifax_top_crimes}
halifax_crime %>%
  group_by(offense_type) %>%
  tally %>%
  ggplot(aes(x = reorder(offense_type, n), y = n)) +
  geom_bar(stat = 'identity', fill = "#0072B2") +
  coord_flip() + 
  labs(x = NULL,
       y = "Number of Crimes",
       title = "Total Number of Crimes by Offense Type") +
  xlab("Crime type") + ylab("Number of crimes") + 
  ggtitle("Total number of crimes by offense type") + 
  theme_minimal()

halifax_crime_tally <- halifax_crime %>%
  group_by(offense_type) %>%
  tally 

halifax_crime %>%
  mutate(clearance_stat = case_when(incident_clearance == "Cleared by Arrest" ~ 1,
                                    incident_clearance != "Cleared by Arrest" ~ 0)
         ) %>%
  group_by(offense_type, clearance_stat) %>%
  summarise(perc_clear = n()) %>%
  group_by(offense_type) %>%
  mutate(perc_clear = perc_clear/sum(perc_clear) * 100) %>%
  filter(clearance_stat == 1) %>%
  inner_join(halifax_crime_tally, by = "offense_type") %>%
  ggplot(aes(x = reorder(offense_type, perc_clear), y = perc_clear)) +
  geom_bar(stat = 'identity', fill = "#0072B2") +
  coord_flip() + 
  labs(x = "Crime Type",
       y = "Percent of Crimes Cleared by Arrest",
       title = "Percent of Crimes Cleared by Offense Type")
  xlab("Crime type") + ylab("Percent of crimes cleared by arrest") + 
  ggtitle("Percent of crimes cleared by\narrest by offense type") + 
  theme_minimal()

```

#### Crime trends by race (total and per capita)

```{r halifax_crime_by_race}
halifax_crime %>%
  filter(offender_race %in% c("Black or African American",
                              "White")) %>%
  group_by(incident_year, offender_race) %>%
  tally %>%
  ggplot(aes(x = incident_year, y = n, color = offender_race)) + 
  geom_line(lwd = 1.1) +
  geom_point(size = 2) + 
  scale_x_continuous(breaks = c(seq(2010, 2019)),
                     labels = c(seq(2010, 2019))) +
  scale_color_manual(values = cbbPalette,
                     labels = c("Black", "White")) + 
  labs(x = NULL,
       y = "Number of Crimes",
       title = "Total Number of Crimes by Race",
       color = "Offender\nRace") +
  lims(y = c(0, 1000))

halifax_pop <- va_pop_by_race[va_pop_by_race$county_cap == "HALIFAX",]

halifax_crime %>%
  filter(offender_race %in% c("Black or African American",
                              "White")) %>%
  group_by(incident_year, offender_race) %>%
  tally %>%
  mutate(crime_per_cap = case_when(offender_race == "Black or African American" ~ n/halifax_pop$pop_Black,
                                   offender_race == "White" ~ n/halifax_pop$pop_White)
         ) %>%
  ggplot(aes(x = incident_year, y = crime_per_cap * 1000, color = offender_race)) + 
  geom_line(lwd = 1.1) +
  geom_point(size = 2) + 
  scale_x_continuous(breaks = c(seq(2010, 2019)),
                     labels = c(seq(2010, 2019))) +
  scale_color_manual(values = cbbPalette,
                     labels = c("Black", "White")) + 
  labs(x = NULL,
       y = "Number of Crimes per Per 1000 People",
       title = "Total Number of Crimes by Race per 1000 People",
       color = "Offender\nRace") +
  lims(y = c(0, 80))

```

#### Clearance rates by race

```{r}
halifax_crime %>%
  filter(offender_race %in% c("Black or African American",
                              "White")) %>%
  mutate(clearance_stat = case_when(incident_clearance == "Cleared by Arrest" ~ 1,
                                    incident_clearance != "Cleared by Arrest" ~ 0)
         ) %>%
  group_by(incident_year, offender_race, clearance_stat) %>%
  summarise(perc_clear = n()) %>%
  group_by(incident_year) %>%
  mutate(perc_clear = perc_clear/sum(perc_clear) * 100) %>%
  filter(clearance_stat == 1) %>%
  ggplot(aes(x = incident_year, y = perc_clear, color = offender_race)) + 
  geom_line(lwd = 1.1) +
  geom_point(size = 2) + 
  scale_x_continuous(breaks = c(seq(2010, 2019)),
                     labels = c(seq(2010, 2019))) +
  scale_color_manual(values = cbbPalette,
                     labels = c("Black", "White")) + 
  labs(x = NULL,
       y = "Percent of Crimes Cleared by Arrest",
       title = "Percent of Crimes Cleared by Arrest by Race",
       color = "Offender\nRace") +
  lims(y = c(0, 50))
  
```

### Comparison of Halifax county to other VA counties

```{r va_county_map_data}
# get VA state map data
states <- map_data("state")
va_state <- subset(states, region == "virginia")

# get VA county map data
counties <- map_data("county")
va_county <- subset(counties, region == "virginia")

va_county$county_cap <- toupper(va_county$subregion)
```

```{r ggplot_setup}
ditch_the_axis <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  legend.position = 'top', 
  legend.justification = 'left',
  legend.direction = 'horizontal'
)

va_base <- ggplot(data = va_state, 
                  mapping = aes(x = long, y = lat, group = group)) +
  coord_fixed(1.1) + 
  geom_polygon(color = "black", fill = "gray")
```

#### All crimes

```{r all_crimes}
county_total <- all_va_crime %>%
  group_by(county_cap) %>%
  tally %>%
  as.data.frame() %>%
  inner_join(va_pop_by_race, by = "county_cap") %>%
  mutate(crime_per_cap = n/total_pop) %>%
  inner_join(va_county, by = "county_cap")

county_total_plot <- va_base +
  geom_polygon(data = county_total, aes(fill = crime_per_cap), color = "white") +
  geom_polygon(color = "black", fill = NA) + 
  geom_text(data = county_total %>% filter(county_cap == "HALIFAX") %>% slice(1), 
            aes(x = long - 0.15, y = lat + 0.2, label = "H")) + 
  scale_fill_viridis_c(trans = "sqrt", alpha = .4) +
  theme_bw() +
  ditch_the_axis + 
  guides(fill = guide_legend(title = "Crimes\nper\ncapita"))

county_total_year <- all_va_crime %>%
  group_by(incident_year, county_cap) %>%
  tally %>%
  as.data.frame() %>%
  inner_join(va_pop_by_race, by = "county_cap") %>%
  mutate(crime_per_cap = n/total_pop) %>%
  inner_join(va_county, by = "county_cap")

halifax_total_year <- county_total_year %>% filter(county_cap == "HALIFAX")

county_total_year_plot <- ggplot(data = county_total_year %>% filter(county_cap != "HALIFAX"), 
                                 aes(x = incident_year, y = crime_per_cap, group = county_cap)) + 
  geom_line(alpha = 0.1) +
  geom_line(data = halifax_total_year, 
            aes(x = incident_year, y = crime_per_cap),
            color = "red", lwd = 1.3) + 
  scale_x_continuous(breaks = c(seq(2010, 2019)),
                     labels = c(seq(2010, 2019))) +
  xlab("Year") + ylab("Crimes per capita") +
  theme_bw()

total_crime_grid <- plot_grid(county_total_plot, county_total_year_plot,
                               nrow = 2)

total_crime_title <- ggdraw() + 
  draw_label("Number of total crimes per capita\nin each county from 2010 to 2019", 
             fontface='bold')
plot_grid(total_crime_title, total_crime_grid, ncol = 1, rel_heights = c(0.1, 1))

```

#### Black crimes

```{r black_crimes}
county_black <- all_va_crime %>%
  filter(offender_race == "Black or African American") %>%
  group_by(county_cap) %>%
  tally %>%
  as.data.frame() %>%
  inner_join(va_pop_by_race, by = "county_cap") %>%
  mutate(black_per_cap = n/pop_Black) %>%
  inner_join(va_county, by = "county_cap")

county_black_plot <- va_base + 
  geom_polygon(data = county_black, aes(fill = black_per_cap), color = "white") +
  geom_polygon(color = "black", fill = NA) +
  geom_text(data = county_black %>% filter(county_cap == "HALIFAX") %>% slice(1), 
            aes(x = long - 0.15, y = lat + 0.2, label = "H")) + 
  scale_fill_viridis_c(trans = "sqrt", alpha = .4) +
  theme_bw() +
  ditch_the_axis + 
  guides(fill = guide_legend(title = "Crimes\nper\ncapita"))

county_black_year <- all_va_crime %>%
  group_by(incident_year, county_cap) %>%
  tally %>%
  as.data.frame() %>%
  inner_join(va_pop_by_race, by = "county_cap") %>%
  mutate(crime_per_cap = n/pop_Black) %>%
  inner_join(va_county, by = "county_cap")

halifax_black_year <- county_black_year %>% filter(county_cap == "HALIFAX")

county_black_year_plot <- ggplot(data = county_black_year %>% filter(county_cap != "HALIFAX"), 
                                 aes(x = incident_year, y = crime_per_cap, group = county_cap)) + 
  geom_line(alpha = 0.1) +
  geom_line(data = halifax_black_year, 
            aes(x = incident_year, y = crime_per_cap),
            color = "red", lwd = 1.3) + 
  scale_x_continuous(breaks = c(seq(2010, 2019)),
                     labels = c(seq(2010, 2019))) +
  ylim(0, 10) + 
  xlab("Year") + ylab("Crimes per capita") +
  theme_bw()

black_crime_grid <- plot_grid(county_black_plot, county_black_year_plot,
                               nrow = 2)

black_crime_title <- ggdraw() + 
  draw_label("Number of Black crimes per capita\nin each county from 2010 to 2019", 
             fontface='bold')
plot_grid(black_crime_title, black_crime_grid, ncol = 1, rel_heights = c(0.1, 1))
```

#### White crimes

```{r white_crimes}
county_white <- all_va_crime %>%
  filter(offender_race == "White") %>%
  group_by(county_cap) %>%
  tally %>%
  as.data.frame() %>%
  inner_join(va_pop_by_race, by = "county_cap") %>%
  mutate(white_per_cap = n/pop_White) %>%
  inner_join(va_county, by = "county_cap")

county_white_plot <- va_base + 
  geom_polygon(data = county_white, aes(fill = white_per_cap), color = "white") +
  geom_polygon(color = "black", fill = NA) +
  geom_text(data = county_white %>% filter(county_cap == "HALIFAX") %>% slice(1), 
            aes(x = long - 0.15, y = lat + 0.2, label = "H")) + 
  scale_fill_viridis_c(trans = "sqrt", alpha = .4) +
  theme_bw() +
  ditch_the_axis +
  guides(fill = guide_legend(title = "Crimes\nper\ncapita"))

county_white_year <- all_va_crime %>%
  group_by(incident_year, county_cap) %>%
  tally %>%
  as.data.frame() %>%
  inner_join(va_pop_by_race, by = "county_cap") %>%
  mutate(crime_per_cap = n/pop_White) %>%
  inner_join(va_county, by = "county_cap")

halifax_white_year <- county_white_year %>% filter(county_cap == "HALIFAX")

county_white_year_plot <- ggplot(data = county_white_year %>% filter(county_cap != "HALIFAX"), 
                                 aes(x = incident_year, y = crime_per_cap, group = county_cap)) + 
  geom_line(alpha = 0.1) +
  geom_line(data = halifax_white_year, 
            aes(x = incident_year, y = crime_per_cap),
            color = "red", lwd = 1.3) + 
  scale_x_continuous(breaks = c(seq(2010, 2019)),
                     labels = c(seq(2010, 2019))) +
  xlab("Year") + ylab("Crimes per capita") +
  theme_bw()

white_crime_grid <- plot_grid(county_white_plot, county_white_year_plot,
                               nrow = 2)

white_crime_title <- ggdraw() + 
  draw_label("Number of White crimes per capita\nin each county from 2010 to 2019", 
             fontface='bold')
plot_grid(white_crime_title, white_crime_grid, ncol = 1, rel_heights = c(0.1, 1))
```

#### All drug crimes

```{r all_drugs}
all_drug <- all_va_crime %>%
  filter(offense_type == "Drug/Narcotic Violations") %>%
  group_by(county_cap) %>%
  tally %>%
  as.data.frame() %>%
  inner_join(va_pop_by_race, by = "county_cap") %>%
  mutate(drug_per_cap = n/total_pop) %>%
  inner_join(va_county, by = "county_cap")

all_drug_plot <- va_base +  
  geom_polygon(data = all_drug, aes(fill = drug_per_cap), color = "white") +
  geom_polygon(color = "black", fill = NA) +
  geom_text(data = all_drug %>% filter(county_cap == "HALIFAX") %>% slice(1), 
            aes(x = long - 0.15, y = lat + 0.2, label = "H")) + 
  scale_fill_viridis_c(trans = "sqrt", alpha = .4) +
  theme_bw() +
  ditch_the_axis + 
  guides(fill = guide_legend(title = "Crimes\nper\ncapita"))

all_drug_year <- all_va_crime %>%
  filter(offense_type == "Drug/Narcotic Violations") %>%
  group_by(incident_year, county_cap) %>%
  tally %>%
  as.data.frame() %>%
  inner_join(va_pop_by_race, by = "county_cap") %>%
  mutate(drug_per_cap = n/total_pop) %>%
  inner_join(va_county, by = "county_cap")

halifax_drug_year <- all_drug_year %>% filter(county_cap == "HALIFAX")

all_drug_year_plot <- ggplot(data = all_drug_year %>% filter(county_cap != "HALIFAX"), 
                                aes(x = incident_year, y = drug_per_cap, group = county_cap)) + 
  geom_line(alpha = 0.1) +
  geom_line(data = halifax_drug_year, 
            aes(x = incident_year, y = drug_per_cap),
            color = "red", lwd = 1.3) + 
  scale_x_continuous(breaks = c(seq(2010, 2019)),
                     labels = c(seq(2010, 2019))) +
  xlab("Year") + ylab("Crimes per capita") +
  theme_bw()

all_drug_grid <- plot_grid(all_drug_plot, all_drug_year_plot,
                               nrow = 2)

all_drug_title <- ggdraw() + 
  draw_label("Number of total drug crimes per capita\nin each county from 2010 to 2019", 
             fontface='bold')
plot_grid(all_drug_title, all_drug_grid, ncol = 1, rel_heights = c(0.1, 1))

```

#### Black drug crimes

```{r black_drugs}
black_drug <- all_va_crime %>%
  filter(offense_type == "Drug/Narcotic Violations" & 
           offender_race == "Black or African American") %>%
  group_by(county_cap) %>%
  tally %>%
  as.data.frame() %>%
  inner_join(va_pop_by_race, by = "county_cap") %>%
  mutate(black_per_cap = n/pop_Black) %>%
  inner_join(va_county, by = "county_cap")

black_drug_plot <- va_base +  
  geom_polygon(data = black_drug, aes(fill = black_per_cap), color = "white") +
  geom_polygon(color = "black", fill = NA) +
  geom_text(data = black_drug %>% filter(county_cap == "HALIFAX") %>% slice(1), 
            aes(x = long - 0.15, y = lat + 0.2, label = "H")) + 
  scale_fill_viridis_c(trans = "sqrt", alpha = .4) +
  theme_bw() +
  ditch_the_axis + 
  guides(fill = guide_legend(title = "Crimes\nper\ncapita"))

black_drug_year <- all_va_crime %>%
  filter(offense_type == "Drug/Narcotic Violations" & 
           offender_race == "Black or African American") %>%
  group_by(incident_year, county_cap) %>%
  tally %>%
  as.data.frame() %>%
  inner_join(va_pop_by_race, by = "county_cap") %>%
  mutate(drug_per_cap = n/pop_Black) %>%
  inner_join(va_county, by = "county_cap")

halifax_black_drug_year <- black_drug_year %>% filter(county_cap == "HALIFAX")

black_drug_year_plot <- ggplot(data = black_drug_year %>% filter(county_cap != "HALIFAX"), 
                                  aes(x = incident_year, y = drug_per_cap, group = county_cap)) + 
  geom_line(alpha = 0.1) +
  geom_line(data = halifax_black_drug_year, 
            aes(x = incident_year, y = drug_per_cap),
            color = "red", lwd = 1.3) + 
  scale_x_continuous(breaks = c(seq(2010, 2019)),
                     labels = c(seq(2010, 2019))) +
  ylim(0, 0.1) + 
  xlab("Year") + ylab("Crimes per capita") +
  theme_bw()

black_drug_grid <- plot_grid(black_drug_plot, black_drug_year_plot,
                               nrow = 2)

black_drug_title <- ggdraw() + 
  draw_label("Number of Black drug crimes per capita\nin each county from 2010 to 2019", 
             fontface='bold')
plot_grid(black_drug_title, black_drug_grid, ncol = 1, rel_heights = c(0.1, 1))

```

#### White drug crimes

```{r white_drugs}
white_drug <- all_va_crime %>%
  filter(offense_type == "Drug/Narcotic Violations" & 
           offender_race == "White") %>%
  group_by(county_cap) %>%
  tally %>%
  as.data.frame() %>%
  inner_join(va_pop_by_race, by = "county_cap") %>%
  mutate(white_per_cap = n/pop_White) %>%
  inner_join(va_county, by = "county_cap")

white_drug_plot <- va_base +  
  geom_polygon(data = white_drug, aes(fill = white_per_cap), color = "white") +
  geom_polygon(color = "black", fill = NA) +
  geom_text(data = white_drug %>% filter(county_cap == "HALIFAX") %>% slice(1), 
            aes(x = long - 0.15, y = lat + 0.2, label = "H")) + 
  scale_fill_viridis_c(trans = "sqrt", alpha = .4) +
  theme_bw() +
  ditch_the_axis + 
  guides(fill = guide_legend(title = "Crimes\nper\ncapita"))

white_drug_year <- all_va_crime %>%
  filter(offense_type == "Drug/Narcotic Violations" & 
           offender_race == "White") %>%
  group_by(incident_year, county_cap) %>%
  tally %>%
  as.data.frame() %>%
  inner_join(va_pop_by_race, by = "county_cap") %>%
  mutate(drug_per_cap = n/pop_White) %>%
  inner_join(va_county, by = "county_cap")

halifax_white_drug_year <- white_drug_year %>% filter(county_cap == "HALIFAX")

white_drug_year_plot <- ggplot(data = white_drug_year %>% filter(county_cap != "HALIFAX"), 
                               aes(x = incident_year, y = drug_per_cap, group = county_cap)) + 
  geom_line(alpha = 0.1) +
  geom_line(data = halifax_white_drug_year, 
            aes(x = incident_year, y = drug_per_cap),
            color = "red", lwd = 1.3) + 
  scale_x_continuous(breaks = c(seq(2010, 2019)),
                     labels = c(seq(2010, 2019))) +
  xlab("Year") + ylab("Crimes per capita") +
  theme_bw()

white_drug_grid <- plot_grid(white_drug_plot, white_drug_year_plot,
                               nrow = 2)

white_drug_title <- ggdraw() + 
  draw_label("Number of white drug crimes per capita\nin each county from 2010 to 2019", 
             fontface='bold')
plot_grid(white_drug_title, white_drug_grid, ncol = 1, rel_heights = c(0.1, 1))
```
