#Loading Packages into R
library(tidycensus)
library(sp)
library(tidyverse)
library(sf)
library(mapview)
library(readr)
library(readxl)
library(choroplethr)
library(ggplot2)
library(ggspatial)
library(leaflet)
library(osmdata)
library(plotly)
library(tigris)
library(acs)

#Loading ACS variables and ACS/Decennial Surveys
ACS5_variables_detailed <- load_variables(year = "2018", dataset = "acs5", cache = TRUE)
ACS5_variables_subject <- load_variables(year = "2018", dataset = "acs5/subject", cache = TRUE)
ACS5_variables_profile <- load_variables(year = "2018", dataset = "acs5/profile", cache = TRUE)
ACS5_variables_cprofile <- load_variables(year = "2018", dataset = "acs5/cprofile", cache = TRUE)
VA_acs <- get_acs(geography = "tracts", year = 2018, geometry = TRUE, state = "VA")
VA_dec <- get_decennial(geography = "tracts", year = 2010, geometry = TRUE, state = "VA")

#Importing Halifax based datasets
Halifax_demographics <- get_acs(geography = "county", table = "DP05", year = 2018, geometry = TRUE, state = "VA", county = "Halifax", cache_table = TRUE)
Halifax_income <- get_acs(geography = "county", table = "S1901", year = 2018, geometry = TRUE, state = "VA", county = "Halifax", cache_table = TRUE)
Halifax_house_value <- get_acs(geography = "county", table = "K202509", year = 2018, geometry = TRUE, state = "VA", county = "Halifax", cache_table = TRUE)
Halifax_transportation <- get_acs(geography = "county", table = "S0802", year = 2018, geometry = TRUE, state = "VA", county = "Halifax", cache_table = TRUE)
Halifax_travel_time <- get_acs(geography = "county", table = "B08303", year = 2018, geometry = TRUE, state = "VA", county = "Halifax", cache_table = TRUE)
Halifax_food_stamps <-  get_acs(geography = "county", table = "S2201", year = 2018, geometry = TRUE, state = "VA", county = "Halifax", cache_table = TRUE)
Halifax_education <- get_acs(geography = "county", table = "S1501", year = 2018, geometry = TRUE, state = "VA", county = "Halifax", cache_table = TRUE)
Halifax_poverty <- get_acs(geography = "county", table = "S1701", year = 2018, geometry = TRUE, state = "VA", county = "Halifax", cache_table = TRUE)
Halifax_school_enrollment <- get_acs(geography = "county", table = "S1401", year = 2018, geometry = TRUE, state = "VA", county = "Halifax", cache_table = TRUE)
Halifax_health_insurance <- get_acs(geography = "county", table = "S2701", year = 2018, geometry = TRUE, state = "VA", county = "Halifax", cache_table = TRUE)
